apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: multiplenamespacefederations.federation.raffa.systems
spec:
  group: federation.raffa.systems
  names:
    kind: MultipleNamespaceFederation
    listKind: MultipleNamespaceFederationList
    plural: multiplenamespacefederations
    singular: multiplenamespacefederation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusters:
              items:
                type: string
              type: array
            namespaceSelector:
              type: object
          required:
          - namespaceSelector
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
