apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: replicasets.apps
spec:
  federatedType:
    group: types.federation.k8s.io
    kind: FederatedReplicaSet
    pluralName: federatedreplicasets
    version: v1alpha1
  namespaced: true
  propagationEnabled: true
  target:
    group: apps
    kind: ReplicaSet
    pluralName: replicasets
    version: v1