apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: services
spec:
  federatedType:
    group: types.federation.k8s.io
    kind: FederatedService
    pluralName: federatedservices
    version: v1alpha1
  namespaced: true
  propagationEnabled: true
  target:
    kind: Service
    pluralName: services
    version: v1