apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: serviceaccounts
spec:
  federatedType:
    group: types.federation.k8s.io
    kind: FederatedServiceAccount
    pluralName: federatedserviceaccounts
    version: v1alpha1
  namespaced: true
  propagationEnabled: true
  target:
    kind: ServiceAccount
    pluralName: serviceaccounts
    version: v1