apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: deployments.apps
spec:
  federatedType:
    group: types.federation.k8s.io
    kind: FederatedDeployment
    pluralName: federateddeployments
    version: v1alpha1
  namespaced: true
  propagationEnabled: true
  target:
    group: apps
    kind: Deployment
    pluralName: deployments
    version: v1