apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: jobs.batch
spec:
  federatedType:
    group: types.federation.k8s.io
    kind: FederatedJob
    pluralName: federatedjobs
    version: v1alpha1
  namespaced: true
  propagationEnabled: true
  target:
    group: batch
    kind: Job
    pluralName: jobs
    version: v1