apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: secrets
spec:
  federatedType:
    group: types.federation.k8s.io
    kind: FederatedSecret
    pluralName: federatedsecrets
    version: v1alpha1
  namespaced: true
  propagationEnabled: true
  target:
    kind: Secret
    pluralName: secrets
    version: v1