apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: namespaces
spec:
  federatedType:
    group: types.federation.k8s.io
    kind: FederatedNamespace
    pluralName: federatednamespaces
    version: v1alpha1
  namespaced: false
  propagationEnabled: true
  target:
    kind: Namespace
    pluralName: namespaces
    version: v1