apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: ingresses.extensions
spec:
  federatedType:
    group: types.federation.k8s.io
    kind: FederatedIngress
    pluralName: federatedingresses
    version: v1alpha1
  namespaced: true
  propagationEnabled: true
  target:
    group: extensions
    kind: Ingress
    pluralName: ingresses
    version: v1beta1