apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: configmaps
spec:
  federatedType:
    group: types.federation.k8s.io
    kind: FederatedConfigMap
    pluralName: federatedconfigmaps
    version: v1alpha1
  namespaced: true
  propagationEnabled: true
  target:
    kind: ConfigMap
    pluralName: configmaps
    version: v1